//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital163.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public string врач { get; set; }
        public string процедура { get; set; }
        public System.DateTime дата { get; set; }
        public string диагноз { get; set; }
        public int ID { get; set; }
    }
}
