//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital163.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class th_V
    {
        public string TitleService { get; set; }
        public string fio { get; set; }
        public System.DateTime data { get; set; }
    }
}
