//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital163.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class two_V
    {
        public string full_name { get; set; }
        public string Title_Service { get; set; }
        public string full_name__employee { get; set; }
        public string DepartamentName { get; set; }
    }
}
